name: Record YouTube Video and Release

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "URL del video de YouTube"
        required: true
        type: string

jobs:
  record-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias necesarias (Puppeteer, FFmpeg, Xvfb, puppeteer-stream)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            gnupg \
            fonts-ipafont-gothic \
            fonts-wqy-zenhei \
            fonts-thai-tlwg \
            fonts-kacst \
            fonts-freefont-ttf \
            libxss1 \
            pulseaudio \
            xvfb \
            google-chrome-stable \
            ffmpeg \
            --no-install-recommends

          # Instalar dependencias de Puppeteer y puppeteer-stream
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth puppeteer-stream

      - name: Iniciar servidor X virtual (Xvfb)
        run: |
          Xvfb :99 -screen 0 1280x720x24 -ac &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Grabar video desde YouTube usando puppeteer-stream
        env:
          YOUTUBE_URL: ${{ inputs.youtube_url }}
        run: |
          cat <<EOF > record.js
          const puppeteer = require('puppeteer-extra');
          const puppeteerStream = require('puppeteer-stream');
          const stealthPlugin = require('puppeteer-extra-plugin-stealth');
          puppeteer.use(stealthPlugin());

          (async () => {
              const browser = await puppeteer.launch({
                  headless: true, // Modo headless
                  args: [
                      '--no-sandbox',
                      '--disable-setuid-sandbox',
                      '--enable-usermedia-screen_capturing',
                      '--allow-http-screen-capture',
                      '--use-fake-ui-for-media-stream',
                      '--use-fake-device-for-media-stream',
                      '--autoplay-policy=no-user-gesture-required',
                      '--enable-usermedia-screen-capturing'
                  ],
                  defaultViewport: null,
                  executablePath: '/usr/bin/google-chrome-stable'
              });

              const page = await browser.newPage();
              console.log("Cargando YouTube...");
              await page.goto(process.env.YOUTUBE_URL, { waitUntil: 'networkidle2' });

              console.log("Esperando a que el video cargue...");
              await page.waitForSelector("video", { timeout: 60000 });

              // Inicia la captura de audio y video con puppeteer-stream
              const { stream, video } = await puppeteerStream(page);

              // Inicia la reproducci칩n del video
              await page.evaluate(() => {
                  let video = document.querySelector("video");
                  video.play();
                  video.volume = 1.0;
              });

              console.log("Esperando a que el video empiece a reproducirse...");
              await page.waitForFunction(() => {
                  const video = document.querySelector('video');
                  return video && !video.paused && video.currentTime > 0;
              }, { timeout: 60000 });

              console.log("Grabando durante 60 segundos...");
              await page.waitFor(() => new Promise(resolve => setTimeout(resolve, 60000))); // Esperar 60s

              console.log("Finalizando grabaci칩n...");
              stream.destroy();

              await browser.close();
          })();
          EOF

          node record.js

      - name: Mejorar calidad con FFmpeg
        run: |
          ffmpeg -i video.mp4 -vf "scale=1280:720:flags=lanczos" -c:v libx264 -preset slow -crf 18 -c:a aac -b:a 192k video_final.mp4

      - name: Subir video como release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_NAME=$(date +"%Y-%m-%d")
          gh release create "$RELEASE_NAME" "video_final.mp4" --title "Video grabado el $RELEASE_NAME" --notes "Grabaci칩n autom치tica desde YouTube"
