name: Record Webpage Media

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "Webpage URL to record"
        required: true
        type: string

jobs:
  record:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth fs-extra

      - name: Create Puppeteer Script
        run: |
          $script = @"
          const puppeteer = require('puppeteer-extra');
          const StealthPlugin = require('puppeteer-extra-plugin-stealth');
          const fs = require('fs-extra');

          puppeteer.use(StealthPlugin());

          (async () => {
              const browser = await puppeteer.launch({
                  executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
                  headless: false,
                  args: [
                      '--autoplay-policy=no-user-gesture-required',
                      '--use-fake-ui-for-media-stream',
                      '--use-fake-device-for-media-stream',
                      '--enable-usermedia-screen-capturing',
                      '--allow-file-access-from-files',
                      '--disable-web-security',
                      '--no-sandbox',
                      '--disable-setuid-sandbox'
                  ]
              });

              const page = await browser.newPage();
              await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');
              await page.setViewport({ width: 1280, height: 720 });

              const url = process.env.TARGET_URL;
              console.log("Navigating to:", url);
              await page.goto(url, { waitUntil: 'networkidle2' });

              // Accept cookies if prompted
              try {
                  await page.waitForSelector('[aria-label="Accept Cookies"], button:contains("Accept")', { timeout: 5000 });
                  await page.click('[aria-label="Accept Cookies"], button:contains("Accept")');
              } catch (err) {
                  console.log('No cookie popup found.');
              }

              // Find a video element on the page
              const hasVideo = await page.evaluate(() => {
                  return !!document.querySelector('video');
              });

              if (!hasVideo) {
                  console.error('No video element found. Exiting...');
                  await browser.close();
                  process.exit(1);
              }

              console.log('Video found! Injecting recording script...');

              await page.evaluate(() => {
                  window.startRecording = () => {
                      return new Promise((resolve) => {
                          const video = document.querySelector('video');
                          if (!video) {
                              console.error('No video found.');
                              return;
                          }

                          const stream = video.captureStream();
                          const audioCtx = new AudioContext();
                          const dest = audioCtx.createMediaStreamDestination();
                          const videoTracks = stream.getVideoTracks();
                          const audioTracks = [];

                          if (video.mozCaptureStream) {
                              audioTracks.push(...video.mozCaptureStream().getAudioTracks());
                          } else {
                              console.warn('No direct audio capture, using system audio workaround.');
                          }

                          if (audioTracks.length > 0) {
                              audioTracks.forEach(track => dest.stream.addTrack(track));
                              stream.addTrack(dest.stream.getAudioTracks()[0]);
                          }

                          const recorder = new MediaRecorder(stream, { mimeType: 'video/webm; codecs=vp9,opus' });
                          const chunks = [];

                          recorder.ondataavailable = event => chunks.push(event.data);
                          recorder.onstop = () => {
                              const blob = new Blob(chunks, { type: 'video/webm' });
                              const reader = new FileReader();
                              reader.onload = () => resolve(reader.result);
                              reader.readAsArrayBuffer(blob);
                          };

                          recorder.start();
                          setTimeout(() => recorder.stop(), 20000);
                      });
                  };
              });

              const videoBuffer = await page.evaluate(() => window.startRecording());

              if (!videoBuffer) {
                  console.error('Recording failed.');
                  await browser.close();
                  process.exit(1);
              }

              console.log('Recording finished. Saving file...');
              fs.writeFileSync('recording.webm', Buffer.from(videoBuffer));
              console.log('Recording saved: recording.webm');

              await browser.close();
          })();
          "@
          $script | Set-Content -Path record.js -Encoding utf8
        shell: pwsh

      - name: Run Puppeteer & Record Video
        run: node record.js
        env:
          TARGET_URL: ${{ inputs.target_url }}

      - name: Upload Recording to GitHub Releases
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: recording.webm
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
